### ISSUE TITLE
Consider if we can design this in a way that's useful for Vega too.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-tooltip#10]
A comment from @arvind  – at its simplest form, this plugin is useful for Vega too. 

Maybe we can design make this more generic, while optionallly supporting some vega-lite specific features?

**Comment by kanitw** [comment]
@ZeningQu  Probably worth trying the current code with example vega visualization and see if it works well.  

If yes, we might want to revise our API to take `view` as the main parameter and take another `opt` parameter that we can specify `mode: "vega-lite"` and other VL specific properties.

**Comment by ZeningQu** [comment]
I just tried out various Vega examples. I think tooltip will be great for many chart types :) I'm going to work on API and select fields next.

![arc](https://cloud.githubusercontent.com/assets/822034/13551097/238cf4d0-e2e3-11e5-93f4-5d93ec15ef1b.png)

![choropleth](https://cloud.githubusercontent.com/assets/822034/13551099/282aabe0-e2e3-11e5-9b21-495689009098.png)

![force](https://cloud.githubusercontent.com/assets/822034/13551124/28e7b69e-e2e4-11e5-8f17-f109edc7d8ac.png)

![heatmap](https://cloud.githubusercontent.com/assets/822034/13551126/2db7b1ce-e2e4-11e5-8acc-9de232f41a40.png)

**Comment by domoritz** [comment]
As you can see formatting is quite important here as well. We should have formatters for objects, numbers, and dates.

**Comment by ZeningQu** [comment]
> We should have formatters for objects, numbers, and dates.

Agreed.

**Comment by arvind** [comment]
I also recommend coordinating with @jhoffswell to ensure the tooltip API is sufficiently expressive, if she wishes to reuse it for the vega-debugger.

**Comment by ZeningQu** [comment]
@arvind @jhoffswell 

Here's a demo of the tooltip plugin working with Vega visualizations (Vega examples are at the second half of the page):
http://vega.github.io/vega-lite-tooltip/


Here's documentation on how to use the tooltip library:
[Creating Your Tooltip](https://github.com/vega/vega-lite-tooltip/blob/zqu/many-small-quick-fixes/docs/creating_your_tooltip.md)
[Customizing Your Tooltip](https://github.com/vega/vega-lite-tooltip/blob/zqu/many-small-quick-fixes/docs/customizing_your_tooltip.md)

Please feel free to try the tooltip and comment from Vega's perspective, and please let me know if there's anything unclear in the docs!

**Comment by arvind** [comment]
Very cool!
