### ISSUE TITLE
Use JS?

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-tooltip#12]
Since the code is <100 lines and does not leverage any typings, using typescript simply complicates things.   

For small codebase like this, using only JS will have the benefit that you have the ready-to-use file in the repo without requiring complicated deploy system.

**Comment by domoritz** [comment]
I disagree. The build only involves running `tsc`. That's pretty low effort you get type information for vega-lite for example. 

We could put the generated js file in the repo and don't have a separate deploy process.

**Comment by kanitw** [comment]
Still you're requiring Typescript, the typings files for 40-line of codes, which doesn't justify the gain from the compilation.

**Comment by kanitw** [comment]
Instead of "why removing TS?", I would like to hear your opinion why it makes sense why should we use it in this repo?

**Comment by kanitw** [comment]
Especially if this is becoming vega-tooltips rather than vega-lite-tooltips ...

**Comment by domoritz** [comment]
I just wanted to say consistency ;-) 

I guess what's missing from the tooltip plugin right now is a way to specify which fields should actually be shown in the tooltip. Maybe we introduce a channel for that at some point. Then we will be happy to have the plugin in ts. 

Having said that, it doesn't matter much at this point for the reasons you said.

**Comment by ZeningQu** [comment]
Part of #16.
