### ISSUE TITLE
Alias for field name

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#18]
It would be good if we can allow users to specify custom names for tooltip field names. I can pass in alias in the `opt` object through the API

**Comment by kanitw** [comment]
Hmm what do you mean?   Do you mean something like replacing variable name `"Cost_Total"` with `"Cost Total"`?

**Comment by ZeningQu** [comment]
@kanitw exactly, so in the example below, user may want to rename `Miles_per_Gallon` to `Miles per Gallon` and `Weight_in_lbs` to `Weight(lbs)`.

![untitled](https://cloud.githubusercontent.com/assets/822034/13588793/7d7060ae-e487-11e5-93d8-73466d930d6f.jpg)

Would that be helpful?

**Comment by kanitw** [comment]
You can call that `fieldTitle`

**Comment by ZeningQu** [comment]
Part of #16.
