### ISSUE TITLE
vlTooltip default should be fieldDefs

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#22]
Currently, for Vega-Lite visualizations, if no `options` is passed in the tooltip will show all top-level fields an `item` has.

But we should make it so that if no `options` is passed in, tooltip will only show fields that's used in the visualization, i.e. `vl.spec.fieldDefs`.

The spirit is that we want the user to specify as little as possible, but make the result look as good as possible.

**Comment by kanitw** [comment]
@domoritz  If I remember correctly, last friday we say  that the best default is to show all available data, right?

**Comment by ZeningQu** [comment]
> If I remember correctly, last friday we say that the best default is to show all available data, right?

Yes and this was based on the new advances in Vega-Lite that you guys made. So I'm closing this issue for now. Please re-open if you see fit.
