### ISSUE TITLE
Move tooltip to vl & vg namespaces?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#23]
Right now the APIs are
`vlTooltip.linkToView(view, spec, opt)` 
and 
`vgTooltip.linkToView(view, opt)`. 

Potentially we want to move the tooltip to `vl` and `vg` namespaces (?) Then the APIs will become
`vl.tooltip(view, spec, opt)`
and 
`vg.tooltip(view, opt)`

**Comment by domoritz** [comment]
Look at how vega embed adds to the vg namespace. Maybe we need to change vega lite.

**Comment by kanitw** [comment]
for now, why not `.link` rather than `linkToView`

**Comment by domoritz** [comment]
Let's get this right and not change it until then.

**Comment by ZeningQu** [comment]
I just tried this in `vg-tooltip.js`:
```js
window.vg.tooltip = function(vgView, options) {...};
window.vl.tooltip = function(vgView, vlSpec, options) {...};
```
Then in `examples.js` I can call the APIs
```js
vl.tooltip(result.view, vlSpec, options);
vg.tooltip(view, options);
```
This gives us the APIs under `vg` and `vl` namespaces. 

I haven't checked how `vg.embed` does it but will do so soon.

**Comment by ZeningQu** [comment]
This is part of PR #16.

`vg.embed` use `browserify` to export `embed`. Our tooltip library has only one js file, so in #16 I'm not using `browserify`.

In #16 I'm adding `tooltip` to `window.vg` and `window.vl`.

If the tooltip library grows larger, I can split the one js file into modules and use `browserify` to export.

**Comment by ZeningQu** [comment]
Close as part of PR #16
