### ISSUE TITLE
Clean up tooltip content for binned fields

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#29]
Related issue: https://github.com/vega/vega-lite-ui/issues/167

**Comment by ZeningQu** [comment]
Right now for binned fields tooltip shows: `start`, `mid`, `end`, and `range`. I also notice sometimes `range` can be empty. 

When `range` is available, we should show field name and range. When `range` is not available, we should use `start` and `end` to compute a range for tooltip to display (?)

*Case 1* 
![bin1](https://cloud.githubusercontent.com/assets/822034/14391443/e35faab2-fd70-11e5-90b6-a72284ace44f.png)
Tooltip should show: `Rotten_Tomatoes_Rating: 90-100`, `IMDB_Rating: 6-7`

*Case 2*
![bin2](https://cloud.githubusercontent.com/assets/822034/14391479/08de74e4-fd71-11e5-8c97-3dffaca4e96a.png)
Tooltip should show: `Acceleration: 10-15`

*Case 3*
![bin3point](https://cloud.githubusercontent.com/assets/822034/14391497/1c5af394-fd71-11e5-8468-6fd06783b1cb.png)
Tooltip should show: `Acceleration: 15-20`

**Comment by kanitw** [comment]
Why dont you just read start and end and always produce one row that shows
range and make thhe label just say bin_x

People dont need 3-4 rows to understand one data field.

**Comment by ZeningQu** [comment]
This is part of PR #36.
