### ISSUE TITLE
Customize tooltip shape?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#31]
Right now tooltip is a rectangle with 3px rounded corners. It would be nice to express more shapes (e.g. bubble?)

**Comment by kanitw** [comment]
You might want to add a few line to support customizing the tooltip div's
css.

I dont think bubble is worth spending time on as it does not lead to better
understanding of the data and introduces unnecessary complexity to the
logic.

**Comment by ZeningQu** [comment]
I wrote in README.md that you can overwrite the `.vg-tooltip` class in user's own css.
