### ISSUE TITLE
Mouse hover color change

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-lite-tooltip#33]
Hover colors would be a nice complement to tooltip, especially when data is dense. With hover color I can actually see which mark is I'm actually looking at.

![point2](https://cloud.githubusercontent.com/assets/822034/14392888/ad0b16ec-fd78-11e5-9fe3-5442f8e277bd.png)

![bin3point](https://cloud.githubusercontent.com/assets/822034/14392886/a993c6a8-fd78-11e5-8579-5cb704a0eb7d.png)

**Comment by kanitw** [comment]
This seems like some thing that users can modify the spec by default.  I don't think if the tooltip plugin need to automatically modify the spec.   

I would say this might be a useful future feature, but let's not worry but it for now.
