### ISSUE TITLE
Simpler API

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-tooltip#5]
- [x] result/`view` object from vega embed

**Comment by kanitw** [comment]
- [ ] take original vega spec in so we can infer time/numberFormat
- [ ] result/view object from vega embed

- [ ] option to show only some fields in the tooltip

**Comment by ZeningQu** [comment]
`vg.parse.spec` callback takes `view`
`vg.embed` callback takes `result` which contains the `view` and the parsed `spec`
So the tooltip function will take `view` as a parameter.

**Comment by ZeningQu** [comment]
Related issue #10

**Comment by ZeningQu** [comment]
As of today's (March 7, 2016) discussion, the tooltip APIs should be:

> /* for Vega
> @param view Vega view
> @opt object of options {"fields": [
> "field": ...,
> "format": ...,
> "type": "date"/"number"/"object"]}
> */
> vg.tooltip(view, opt)

> /* for Vega-Lite */
> vl.tooltip(view, vlSpec, opt)

**Comment by ZeningQu** [comment]
Fixed as part of #16.
