### ISSUE TITLE
Correctly format time.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-tooltip#6]
- [x] take original vega-lite `spec` as input
- [x] import `datalib`

- [x] read timeUnit so we can set timeFormat
- [x] read `config.numberFormat` so we use the correct numberFormat

**Comment by ZeningQu** [comment]
Is there a way for me to re-use the `export function format(timeUnit: TimeUnit, abbreviated = false)` function in Vega-Lite `time.ts`? I need to do the same thing: translating VL `timeUnit` to the format that's used by VL axis labels.

**Comment by kanitw** [comment]
The right way is to refactor Vega-Lite and move that to src/timeunit.ts (and fix all its reference) so that you can refer to it from `vl.timeUnit.format`.

**Comment by ZeningQu** [comment]
Alright, I will do that in Vega-Lite :) Before that happens & gets merged, I will just pass in string specifiers like `%B`, `%A` through `options`

**Comment by kanitw** [comment]
> Before that happens & gets merged, I will just pass in string specifiers like %B, %A through options

Why wasting your time just for waiting that to get merged?

**Comment by ZeningQu** [comment]
Fixed as part of #16. 

We are formatting time based on (1) time format user provided in options, (2) timeUnit from VLSpec, (3) datalib auto time format. 

We are formatting number based on (1) number format user provided in options, (2) numberFormat from VLSpec, (3) datalib auto number format.

**Comment by kanitw** [comment]
> We are formatting time based on (1) time format user provided in options, (2) timeUnit from VLSpec, (3) datalib auto time format.

why not including `timeFormat` in VL?

**Comment by ZeningQu** [comment]
> why not including `timeFormat` in VL?

Ahhh right, I will include that! Thanks!

**Comment by ZeningQu** [comment]
Close as I added `vlSpec.config.timeFormat` in the supplement process. This will be part of PR #16.
