### ISSUE TITLE
option to show only some fields in the tooltip

### ISSUE THREAD

**Issue by kanitw** [vega/vega-lite-tooltip#8]
- two ways
  - [ ] add `tooltip` channel
  - [ ] For the tooltip API that gets call inside `vg.embed` or `vg.parse.spec`, add a third `tooltip: FieldDef[]` parameters to the API (1st=view, 2nd=spec) .  
     - (Of course only field def that matches fields in the spec would be displayed.) 
     - this mean you the spec must have all fields you want to show in tooltip already

**Idea** 
- [ ] This plugin becomes `vg.embedVegaLiteWithTooltip(..embedparams.., tooltips, callback)`

**Comment by kanitw** [comment]
@domoritz  Good that you bring that up, because this is one thing that I start thinking that tooltip is tricky.   I wonder if we should add a channel that has no effect on normal Vega-Lite without this plugin.  This seems like a bad abstraction.    Also, how would that works when we have concatenation. 

Alternatively, we can make `tooltips` just a parameter of the tooltip plugin API.

**Comment by kanitw** [comment]
If a field listed in `tooltips` is not a part of an aggregate spec, then we show nothing.

**Comment by ZeningQu** [comment]
as we discuss today:
- [ ] for tooltip on Vega, we should have option to show only some fields in the tooltip
- [ ] for tooltip on Vega-Lite, we show all fields in the spec

**Comment by kanitw** [comment]
@ZeningQu 

> for tooltip on Vega, we should have option to show only some fields in the tooltip

 **I don't think  we discussed this yesterday**

--------------

For the first version, let's say

- Vega:  show all fields in the data
- Vega-Lite: show all fields in the spec by default, but we can have "opt.showAllFields" as an option.  

and punt on this.  
--------------

If we want to have option to show only some fields in the tooltip, I do not see why we should not have it for both Vega and Vega-Lite.  That said, it is unclear if the support option for showing only some fields should be an inclusive predicate (specify fields to include) or exclusive predicate (specify fields to exclude).   

I'm leaning toward inclusive predicate and if you have multiple datasets, the list of fields should include fields from all dataset and on the tooltip we only show fields that (1) appears in the hovered data set and (2) appears in the list of fields to show.

**Comment by kanitw** [comment]
Also, IMHO,  this is less important than getting the date right (#6) since all so many of our demo dataset has date but none of them have > 20 fields.

**Comment by domoritz** [comment]
> I don't think we discussed this yesterday

We talked about this yesterday. We need to implement a function that takes a list of fields anyway to implement the projection for vega-lite specs. 

> That said, it is unclear if the support option for showing only some fields should be an inclusive predicate (specify fields to include) or exclusive predicate (specify fields to exclude).

Inclusive++

> Also, IMHO, this is less important than getting the date right (#6) since all so many of our demo dataset has date but none of them have > 20 fields.

Agreed

**Comment by ZeningQu** [comment]
Part of #16. We have the option to show only some fields in the tooltip now.
